version: "3.8"
services:
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./service:/app/service
  worker:
    build: .
    env_file: .env
    command: python -u -c "from service.app import worker; worker.run_worker()"
    depends_on:
      - redis
    volumes:
      - ./service:/app/service
  redis:
    image: redis:7
    ports:
      - "6379:6379"
